---
title: "Shiny analysis - DESeq2"
author: "Tom Kuipers"
output:
  html_document: default
always_allow_html: true
params:
  data_samples:     ""
  data_counts:      ""
  data_annotation:  ""
  setGeneName:      ""
  cpm_value:        ""
  excluded_samples: ""
  design_base:      ""
  design_value:     ""
  matrix_v1:        ""
  matrix_v2:        ""
  alpha:            ""
---


## R Markdown


```{r setup}

if (!require("knitr")) install.packages("knitr")
if (!require("SummarizedExperiment")) install.packages("SummarizedExperiment")
if (!require("DESeq2")) install.packages("DESeq2")
if (!require("tidyr")) install.packages("tidyr")
if (!require("scales")) install.packages("scales")
if (!require("plotly")) install.packages("plotly")

```


```{r variables}
# IMPORT VARIABLES

data_samples <- params$data_samples
data_counts <- params$data_counts
data_annotation <- params$data_annotation
setGeneName <- params$setGeneName
cpm_value <- params$cpm_value
excluded_samples <- params$excluded_samples
design_base <- params$design_base
design_value <- params$design_value
matrix_v1 <- params$matrix_v1
matrix_v2 <- params$matrix_v2
alpha <- params$alpha

```


```{r filterData}
# FILTER DATA IF NESSECARY

#Filter if nessecary
data_samples <- data_samples[!rownames(data_samples) %in% excluded_samples, , drop=FALSE]
data_counts <- data_counts[,!colnames(data_counts) %in% excluded_samples]

```


```{r showVariables}
# SHOW VALUES OF VARIABLES

cpm_value
excluded_samples
alpha
design_base
design_value
matrix_v1
matrix_v2

```


```{r showRawData}
# SHOW RAW DATA

se <- readCountsFromTable(data_counts, data_samples)

alignmentSummaryPlot(se)
complexityPlot(se)

```


```{r filesIntoSE}
# READ ALL FILES INTO SE

se <- readCountsFromTable(data_counts[!grepl('^__', rownames(data_counts)),], data_samples)
se <- addSamplesFromTableToSE(se, data_samples)
if (!is.null(data_annotation)) {
  se <- addAnnotationsFromTableToSE(se, data_annotation)
}

dge <- DGEList(counts = assay(se), samples = colData(se), genes = rowData(se))
dge <- dge[ rowSums( abs( dge$counts ) ) > 1, ]

tempDge <- dge
tempDge$counts <- cpm(dge, log = TRUE)
countDistributionLinePlot(tempDge)

dge <- DGEList(counts = assay(se), samples = colData(se))

```


```{r selectedFeatures}
# GET SELECTED FEATURES

get_design <- createDesign(dge$samples, design_base, design_value, matrix_v1, matrix_v2)
get_design
dge <- relevelSamples(dge, design_base, design_value, matrix_v1, matrix_v2)
design <- model.matrix(eval(parse(text=get_design)), dge$samples)
design

analysis <- DESeqDataSet(se, design = design)
analysis <- analysis[ rowSums( abs( assay(analysis) ) ) > 1, ]

# FILTER IF NESSECARY
selectedFeatures <- rownames( analysis )[ apply( cpm(counts(analysis)), 1, function( v ) sum( v >= cpm_value ) ) >= 1/4 * ncol( counts(analysis) ) ]
analysis <- analysis[selectedFeatures,]

```


```{r startAnalysis}
# START ANALYSIS

analysis <- DESeq(analysis)

```


```{r getNormalizedCounts}
# GET NORMALIZED COUNTS

getSize <- estimateSizeFactors(analysis)
normCounts <- cpm(data.frame(counts(getSize, normalized=TRUE)))
normDge <- DGEList(counts = normCounts, samples = dge$samples)
normDge$counts <- log2(normDge$counts)

countDistributionLinePlot(normDge)
variancePcaPlot(normDge)

```


```{r getResults}
# GET RESULTS

get_matrix1 <- createMatrix(normDge, design_base, design_value, matrix_v1)
get_matrix2 <- createMatrix(normDge, design_base, design_value, matrix_v2)
get_matrix1
get_matrix2

contrast <- createContrast(design, get_matrix1, get_matrix2)
contrast

deTab <- results(analysis, contrast = contrast, alpha = alpha)
summary(deTab)

```


```{r create_deTab}
# CREATE deTab TABLE

deTab <- data.frame(deTab[,c("log2FoldChange", "pvalue", "padj")])
colnames(deTab) <- c("avgLog2FC", "P.Value", "adj.P.Val")
deTab$avgLog2CPM <- rowMeans(normDge$counts)

deTab <- na.omit(deTab)
deTab <- deTab[!is.infinite(rowSums(deTab)),]

# SET DE GENES
deTab$DE <- 0
deTab$DE[deTab$adj.P.Val < alpha & deTab$avgLog2FC < 0] <- -1
deTab$DE[deTab$adj.P.Val < alpha & deTab$avgLog2FC > 0] <- 1

```


```{r addAnnotation}
# ADD ANNOTATION TO deTab

if (!is.null(data_annotation)) {
  deTab <- merge(data_annotation, deTab, by=0, all=FALSE)
  rownames(deTab) <- deTab$Row.names
  deTab$Row.names <- NULL
}

# MAKE BOTH TABLES EQUAL
deTab <- deTab[intersect(rownames(deTab), rownames(normDge$counts)),]
normDge$counts <- normDge$counts[intersect(rownames(deTab), rownames(normDge$counts)),]

```


```{r changeToSymbol}
# CHANGE GENE ID TO SYMBOL IF NESSECARY

if (setGeneName == "symbol" && !is.null(data_annotation)) {
  tempCol <- rownames(deTab)
  rownames(deTab) <- make.names(deTab$geneName, unique=TRUE)
  deTab$geneName <- tempCol
  colnames(deTab)[1] <- "geneId"
  rownames(normDge$counts) <- rownames(deTab)
}

```


```{r showDGEResult}
# SHOW DGE RESULTS

ma_plot(deTab)
pValuePlot(deTab)

```


```{r save}
# SAVE ANALYSIS

save(deTab, normDge, file="analysis.RData")

```


```{r session}
#INFO

sessionInfo()

```
