---
title: "dgeAnalysis - gProfiler2 Enrichment"
author:
- "Developed by LUMC-SASC team:"
- "- Tom Kuipers"
- "- Leon Mei"
- "- Davy Cats"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    theme: paper
always_allow_html: true
params:
  geneList:     ""
  organism:     ""
  significant:  ""
  alfa:         ""
  database:     ""
---


# Load packages

```{r setup}

## Load required packages
suppressPackageStartupMessages({
  library(gprofiler2)
})

```


# Input
## Load input variables

```{r variables}

## Import variables
geneList <- strsplit(params$geneList, "\n")[[1]]
organism <- params$organism
significant <- eval(parse(text = params$significant))
alfa <- params$alfa
database <- params$database

```


## Show input variables

```{r showVariables}

## Values of variables
length(geneList)
organism
significant
alfa
database

```


# Run enrichment

```{r runEnrichment}

## Start enrichment with gProfiler
enrich <- gost(
  query = geneList,
  organism = organism,
  ordered_query = FALSE,
  significant = significant,
  user_threshold = alfa,
  correction_method = "gSCS",
  domain_scope = "annotated",
  sources = database,
  evcodes = TRUE
)

```


# Show results

```{r showResult}

## Show results
enrich$result$query <- ""
gostplot(enrich, capped = FALSE, interactive = TRUE)

```


# Save results

```{r save}

## Save data files
save(enrich, file = "enrichment.RData")

```


# Session info

```{r session}

## Session info
sessionInfo()

```
